const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');
const bcrypt = require('bcryptjs');
const { generateUserSsid } = require('../utils/ssidService');

const Staff = sequelize.define('Staff', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true
  },
  tenantId: {
    type: DataTypes.UUID,
    allowNull: false,
    references: { model: 'Tenants', key: 'id' }
  },
  userId: {
    type: DataTypes.UUID,
    allowNull: true,
    references: { model: 'Users', key: 'id' }
  },
  name: {
    type: DataTypes.STRING(150),
    allowNull: false
  },
  role: {
    type: DataTypes.STRING(50),
    allowNull: false,
    defaultValue: 'waiter'
  },
  phone: {
    type: DataTypes.STRING(20),
    allowNull: true
  },
  email: {
    type: DataTypes.STRING(150),
    allowNull: true
  },
  ssid: {
    type: DataTypes.STRING(24),
    allowNull: true,
    comment: 'Public global SSID generated by backend (format SSXXXXXX)'
  },
  shiftStart: {
    type: DataTypes.STRING(10),
    allowNull: true,
    comment: 'e.g. 09:00'
  },
  shiftEnd: {
    type: DataTypes.STRING(10),
    allowNull: true,
    comment: 'e.g. 18:00'
  },
  isOnDuty: {
    type: DataTypes.BOOLEAN,
    defaultValue: false
  },
  isActive: {
    type: DataTypes.BOOLEAN,
    defaultValue: true
  },
  salary: {
    type: DataTypes.FLOAT,
    allowNull: true
  },
  pin: {
    type: DataTypes.STRING(255),
    allowNull: true,
    comment: '4-digit PIN for staff authorization'
  },
  pinPlain: {
    type: DataTypes.STRING(20),
    allowNull: true,
    comment: 'Display copy of staff PIN for owner-managed UI flows'
  },
  staffId: {
    type: DataTypes.STRING(20),
    allowNull: true,
    comment: 'Unique 6-digit numeric Staff ID'
  }
}, {
  timestamps: true,
  hooks: {
    beforeValidate: async (staff) => {
      if (!staff.ssid) {
        staff.ssid = await generateUserSsid();
      }
    },
    beforeCreate: async (staff) => {
      if (staff.pin && !String(staff.pin).startsWith('$2')) {
        const rawPin = String(staff.pin).trim();
        staff.pinPlain = rawPin;
        staff.pin = await bcrypt.hash(rawPin, 10);
      }
    },
    beforeUpdate: async (staff) => {
      if (staff.changed('pin') && staff.pin && !String(staff.pin).startsWith('$2')) {
        const rawPin = String(staff.pin).trim();
        staff.pinPlain = rawPin;
        staff.pin = await bcrypt.hash(rawPin, 10);
      }
    }
  },
  indexes: [
    { fields: ['tenantId'] },
    { fields: ['userId'] },
    { fields: ['role'] }
  ]
});

Staff.prototype.toJSON = function () {
  const values = { ...this.get() };
  values.pinSet = !!values.pin;
  delete values.pin;
  values.pin = values.pinPlain || null;
  return values;
};

module.exports = Staff;
