const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const Tenant = sequelize.define('Tenant', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true
  },
  ssid: {
    type: DataTypes.STRING(24),
    allowNull: true,
    comment: 'Public global SSID generated by backend (format SSXXXXXX)'
  },
  name: {
    type: DataTypes.STRING(200),
    allowNull: false
  },
  ownerName: {
    type: DataTypes.STRING(150),
    allowNull: false
  },
  email: {
    type: DataTypes.STRING(150),
    allowNull: true
  },
  phone: {
    type: DataTypes.STRING(20),
    allowNull: true
  },
  city: {
    type: DataTypes.STRING(100),
    allowNull: true
  },
  address: {
    type: DataTypes.TEXT,
    allowNull: true
  },
  logo: {
    type: DataTypes.STRING(500),
    allowNull: true,
    comment: 'Cloudinary URL for restaurant logo'
  },
  plan: {
    type: DataTypes.ENUM('starter', 'basic', 'professional', 'enterprise'),
    defaultValue: 'starter'
  },
  status: {
    type: DataTypes.ENUM('Pending Approval', 'Active', 'Suspended', 'Rejected', 'Cancelled'),
    defaultValue: 'Pending Approval'
  },
  outletsCount: {
    type: DataTypes.INTEGER,
    defaultValue: 1
  },
  ownerUsername: {
    type: DataTypes.STRING(100),
    allowNull: true,
    comment: 'Auto-generated login username for the owner'
  },
  ownerTempPassword: {
    type: DataTypes.STRING(100),
    allowNull: true,
    comment: 'Temporary plain-text password shown to Super Admin only. Owner should change after first login.'
  },
  featureFlagsJson: {
    type: DataTypes.TEXT,
    allowNull: true,
    get() {
      const raw = this.getDataValue('featureFlagsJson');
      try { return raw ? JSON.parse(raw) : {}; } catch { return {}; }
    },
    set(val) {
      this.setDataValue('featureFlagsJson', typeof val === 'string' ? val : JSON.stringify(val));
    }
  },
  currencySymbol: {
    type: DataTypes.STRING(10),
    defaultValue: '₹'
  },
  taxRate: {
    type: DataTypes.FLOAT,
    defaultValue: 5.0
  },
  taxName: {
    type: DataTypes.STRING(30),
    defaultValue: 'GST'
  },
  orderWorkflowMode: {
    type: DataTypes.ENUM('WORKFLOW_1', 'WORKFLOW_2'),
    defaultValue: 'WORKFLOW_1'
  }
}, {
  timestamps: true,
  paranoid: true,
  indexes: [
    { fields: ['status'] },
    { fields: ['plan'] }
  ]
});

module.exports = Tenant;
