const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');
const bcrypt = require('bcryptjs');
const { generateUserSsid } = require('../utils/ssidService');

const User = sequelize.define('User', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true
  },
  tenantId: {
    type: DataTypes.UUID,
    allowNull: true,
    references: { model: 'Tenants', key: 'id' }
  },
  name: {
    type: DataTypes.STRING(150),
    allowNull: false
  },
  email: {
    type: DataTypes.STRING(150),
    allowNull: true
  },
  username: {
    type: DataTypes.STRING(100),
    allowNull: true
  },
  ssid: {
    type: DataTypes.STRING(24),
    allowNull: true,
    comment: 'Public global SSID generated by backend (format SSXXXXXX)'
  },
  password: {
    type: DataTypes.STRING(255),
    allowNull: false
  },
  phone: {
    type: DataTypes.STRING(20),
    allowNull: true
  },
  role: {
    type: DataTypes.ENUM('superadmin', 'owner', 'manager', 'cashier', 'waiter', 'kitchen', 'kds'),
    allowNull: false,
    defaultValue: 'owner'
  },
  pin: {
    type: DataTypes.STRING(255),
    allowNull: true,
    comment: 'Quick PIN for POS terminal login'
  },
  staffId: {
    type: DataTypes.STRING(20),
    allowNull: true,
    comment: 'Unique 6-digit numeric Staff ID for terminal login'
  },
  avatar: {
    type: DataTypes.STRING(500),
    allowNull: true
  },
  isActive: {
    type: DataTypes.BOOLEAN,
    defaultValue: true
  },
  isVerified: {
    type: DataTypes.BOOLEAN,
    defaultValue: true
  },
  lastLoginAt: {
    type: DataTypes.DATE,
    allowNull: true
  },
  refreshToken: {
    type: DataTypes.TEXT,
    allowNull: true
  }
}, {
  timestamps: true,
  paranoid: true,
  indexes: [
    { fields: ['email'] },
    { fields: ['username'] },
    { fields: ['tenantId'] },
    { fields: ['role'] },
    { fields: ['isActive'] }
  ],
  hooks: {
    beforeValidate: async (user) => {
      if (!user.ssid) {
        user.ssid = await generateUserSsid();
      }
    },
    beforeCreate: async (user) => {
      if (user.password) {
        user.password = await bcrypt.hash(user.password, 12);
      }
      if (user.pin && !String(user.pin).startsWith('$2')) {
        user.pin = await bcrypt.hash(String(user.pin), 10);
      }
    },
    beforeUpdate: async (user) => {
      if (user.changed('password')) {
        user.password = await bcrypt.hash(user.password, 12);
      }
      if (user.changed('pin') && user.pin && !String(user.pin).startsWith('$2')) {
        user.pin = await bcrypt.hash(String(user.pin), 10);
      }
    }
  }
});

User.prototype.comparePassword = async function (candidatePassword) {
  return bcrypt.compare(candidatePassword, this.password);
};

User.prototype.toJSON = function () {
  const values = { ...this.get() };
  delete values.password;
  delete values.pin;
  delete values.refreshToken;
  return values;
};

module.exports = User;
